### PR TITLE
Add "objectify" option

### PR DESCRIPTION
**Pull request by ELIYAHUT123**
I think it would be nice if there was option to get back an object instead of a list.

Example:
Let's say you running a food delivery company and you save in the DB the details of "meals" and "deliveries".
The result would look something like this:
```
[
    {
        "meals": [
            {
                "id": 1,
                "name": "meal1",
                "description": "description of meal1",
                "price": 200,
            },
            {
                "id": 2,
                "name": "meal2",
                "description": "description of meal2",
                "price": 250,
            }
        ]
    },
    {
        "deliveries": [
            {
                "id": 1,
                "address": "Somewhere",
            },
            {
                "id": 2,
                "address": "Somewhere else",
            }
        ]
   }
]
```
With this kind of result you can't do something like:
```
axios.get(url).then(response => {
    alert(response.data.meals)
})
```
Because response.data is an array.
Instead you will have to iterate through the result and look for an object that has a key "meals".
It's a shame because this is a very common use.

In order to solve it I added is a little flag called "objectify" (a little like "flat").
In case objectify=True you will get something like this:
```
{
    "meals": [
            {
                "id": 1,
                "name": "meal1",
                "description": "description of meal1",
                "price": 200,
            },
            {
                "id": 2,
                "name": "meal2",
                "description": "description of meal2",
                "price": 250,
            }
        ]
        "deliveries": [
            {
                "id": 1,
                "address": "Somewhere",
            },
            {
                "id": 2,
                "address": "Somewhere else",
            }
        ]
}
```
Now you can easily do:
```
axios.get(url).then(response => {
    alert(response.data.meals)
})
```

### CODE REVIEW

**Comment by ELIYAHUT123** [comment]
Is there a way I can see what made the build fail and fix it?
Thanks in advance :)

**Comment by MattBroach** [comment]
Hey, first of all, thank you for your work on this.  I'd been using a similar thing in my personal version (because you're right, it makes __much__ more sense for your average API use case.  I hadn't implemented anything like it in the public version because I didn't want to break anyone's app, but adding the "objectify" flag and making it default to false I think is a great solution.

I'm sorry it's taken me a bit of time to respond -- I'm travelling right now and have had limited internet access.  I'll be back in a week and can give this my full attention, but for the time being here's the traceback from the failed tests.  Incidentally, the tests only failed on Django 1.7 -- those using 1.8 and 1.9 passed fine.  It looks like it's relying on a field that wasn't available pre Django 1.8.  Django 1.7 is no longer officially supported by Django itself, so I could listen to arguments for simply removing it from the test suite -- I'd be curious to hear what users think.  My preference is to maintain backwards compatibility for as long as possible, but if no users of this library are pre 1.8, it's a moot point.

Here's the traceback:
```
Traceback (most recent call last):
  File "/opt/python/3.3.5/lib/python3.3/unittest/case.py", line 384, in _executeTestPart
    function()
  File "/opt/python/3.3.5/lib/python3.3/unittest/loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: drf_multiple_model.tests
Traceback (most recent call last):
  File "/opt/python/3.3.5/lib/python3.3/unittest/loader.py", line 261, in _find_tests
    module = self._get_module_from_name(name)
  File "/opt/python/3.3.5/lib/python3.3/unittest/loader.py", line 239, in _get_module_from_name
    __import__(name)
  File "/home/travis/build/Axiologue/DjangoRestMultipleModels/drf_multiple_model/tests.py", line 7, in <module>
    from rest_framework import serializers, status, renderers, pagination, filters
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/rest_framework/serializers.py", line 19, in <module>
    from django.db.models import DurationField as ModelDurationField
ImportError: cannot import name DurationField
```

**Comment by MattBroach** [comment]
For those who are curious, I have dropped Django 1.7 support from this library.  The bug introduced for Django 1.7 wasn't introduced by this library, but by Django Rest Framework itself, which has also dropped Django 1.7 support.  Since this library depends on DRF, our version support is basically in lockstep with DRF.  This library __may__ work with Django <1.8 and older versions of Django Rest Framework, but I won't be specifically testing for those.

@ELIYAHUT123, your great work is now merged into master, passes all the tests, and is packaged in our 1.8 release.  Thank you!
